env:
  browser: true
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 10
plugins:
  - "@typescript-eslint"
extends:
  - standard
  - "plugin:@typescript-eslint/recommended"
rules:
  # indent is replaced by @typescript-eslint/indent
  indent:
    - off
  "@typescript-eslint/indent":
    - error
    - 2
  "@typescript-eslint/member-delimiter-style":
    - error
    - multiline:
        delimiter: none
  import/order:
    - error
    - newlines-between: always
      alphabetize:
        order: asc
        caseInsensitive: true
  max-len:
    - error
    - code: 120
  comma-dangle:
    - error
    - always-multiline
